name: Test JMeter Action

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run JMeter Action on a test
        uses: arunpunaroor/jmeter-runner-action@v1
        with:
          testFilePath: GrupodeUsuários.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO"